### ISSUE TITLE
docker-compose up failed

### ISSUE THREAD

**Issue by Yukaii** [yoyo930021/Disfactory#10]
### Commands

```bash
cd backend
docker-compose up
```

### Error outputs

```
Starting backend_db_1 ... done
Recreating backend_web_1 ... done
Attaching to backend_db_1, backend_web_1
db_1   | 2019-09-29 02:26:03.056 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2019-09-29 02:26:03.057 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2019-09-29 02:26:03.062 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2019-09-29 02:26:03.103 UTC [22] LOG:  database system was shut down at 2019-09-29 02:25:58 UTC
db_1   | 2019-09-29 02:26:03.112 UTC [1] LOG:  database system is ready to accept connections
web_1  | Watching for file changes with StatReloader
web_1  | Performing system checks...
web_1  | 
web_1  | System check identified no issues (0 silenced).
web_1  | Exception in thread django-main-thread:
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
web_1  |     self.connect()
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
web_1  |     self.connection = self.get_new_connection(conn_params)
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
web_1  |     connection = Database.connect(**conn_params)
web_1  |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
web_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_1  | psycopg2.OperationalError: could not connect to server: Connection refused
web_1  |        Is the server running on host "db" (172.20.0.2) and accepting
web_1  |        TCP/IP connections on port 5423?
```

我要求救 😂

**Comment by Yukaii** [comment]
更正一下，發現在 master branch 沒問題，是在 https://github.com/yoyo930021/Disfactory/pull/9 發現的

**Comment by stegben** [comment]
發了一個  commit 修掉了，原來是我 default 設錯
